---
#
#
- name: Satelite Configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Run the redhat.satellite roles
      ansible.builtin.include_role:
        name: "{{ __include_role['name'] }}"
        apply:
          tags: "{{ __include_role['tags'] }}"
      when: vars[__include_role.var] is defined
      tags: always
      loop_control:
        loop_var: __include_role
      loop:
        - { name: redhat.satellite.organizations, var: satellite_organizations, tags: organizations }
        - { name: redhat.satellite.locations, var: satellite_locations, tags: locations }
        - { name: redhat.satellite.settings, var: satellite_settings, tags: settings }
        - { name: redhat.satellite.manifest, var: satellite_manifest_path, tags: manifest }
        - { name: redhat.satellite.content_credentials, var: satellite_content_credentials, tags: content_credentials }
        - { name: redhat.satellite.repositories, var: satellite_products, tags: repositories }
        - { name: redhat.satellite.sync_plans, var: satellite_sync_plans, tags: sync_plans }
        - { name: redhat.satellite.lifecycle_environments, var: satellite_lifecycle_environments, tags: lifecycle_environments }
        - { name: redhat.satellite.content_views, var: satellite_content_views, tags: content_views }
        - { name: redhat.satellite.domains, var: satellite_domains, tags: domains }
        - { name: redhat.satellite.activation_keys, var: satellite_activation_keys, tags: activation_keys }
        - { name: redhat.satellite.hostgroups, var: satellite_hostgroups, tags: hostgroups }
        - { name: redhat.satellite.subnets, var: satellite_subnets, tags: subnets }
        - { name: redhat.satellite.provisioning_templates, var: satellite_provisioning_templates, tags: provisioning_templates }
        - { name: redhat.satellite.operatingsystems, var: satellite_operatingsystems, tags: operatingsystems }
        - { name: redhat.satellite.auth_sources_ldap, var: satellite_auth_sources_ldap, tags: auth_sources_ldap }
        - { name: redhat.satellite.compute_resources, var: satellite_compute_resources, tags: compute_resourcee }
        - { name: redhat.satellite.compute_profiles, var: satellite_compute_profiles, tags: compute_profiles }
        - { name: redhat.satellite.content_view_version_cleanup, var: satellite_content_view_version_cleanup_keep, tags: content_view_version_cleanup }
        - { name: redhat.satellite.convert2rhel, var: satellite_convert2rhel_manage_subscription, tags: convert2rhel }
...
