---
# Install Red Hat Satellite using the redhat.satellite_operations collection
- name: Satellite Installation
  hosts: all
  become: true
  gather_facts: false
  vars:
    # For satellite configuration we typically connect from where Ansible is running
    # to the Satellite API.  When installing Satellite, we need to connect over ssh
    # We therefore override the ansible_connection string we set in the inventory
    ansible_connection: ssh
  # Technically, not needed as all tasks use FQCN, but useful to track the collections
  # we are using.
  collections:
    - redhat.satellite_operations
    - community.general
    - ansible.posix
    - redhat.rhel_system_roles

  tasks:
    - name: Prepare the Operating System
      tags:
        - os_tasks
      block:
        - name: Register Satellite server to Red Hat using user and password
          ansible.builtin.include_role:
            name: redhat.rhel_system_roles.rhc
            apply:
              tags:
                - os_tasks
          vars:
            rhc_auth:
              login:
                username: "{{ satellite_installer_rhsm_user }}"
                password: "{{ satellite_installer_rhsm_password }}"
            rhc_insights: "{{ satellite_installer_rhc_insights | default(omit) }}"
          tags:
            - always
          when:
            - satellite_installer_rhsm_user is defined
        - name: Set System Purpose
          community.general.redhat_subscription:
            syspurpose: "{{ satellite_installer_syspurpose | default(omit) }}"
          when:
            - satellite_installer_rhsm_user is defined
        - name: Disable all repos before we configure the ones we require
          community.general.rhsm_repository:
            name: '*'
            state: disabled
          when:
            - satellite_installer_dnf_repositories is defined
        - name: Ensure the Satellite repositories are enabled
          community.general.rhsm_repository:
            name: "{{ satellite_installer_dnf_repositories }}"
            state: enabled
          when:
            - satellite_installer_dnf_repositories is defined
        - name: Install the required Satellite packages
          ansible.builtin.package:
            name: "{{ satellite_installer_packages }}"
            state: installed
          when:
            - satellite_installer_packages is defined
        - name: Enable service firewalld and ensure it is not masked
          ansible.builtin.systemd_service:
            name: firewalld.service
            state: started
            enabled: true
            masked: false
          when:
            - ( satellite_installer_firewall_ports is defined ) or
              ( satellite_installer_firewall_services is defined )
        - name: Permanently enable Satellite firewall ports, also enable them immediately if possible
          ansible.posix.firewalld:
            port: "{{ firewall_port }}"
            state: enabled
            permanent: true
            immediate: true
          loop: "{{ satellite_installer_firewall_ports }}"
          loop_control:
            loop_var: firewall_port
          when:
            - satellite_installer_firewall_ports is defined
        - name: Permanently enable Satellite firewall services, also enable them immediately if possible
          ansible.posix.firewalld:
            service: "{{ firewall_service }}"
            state: enabled
            permanent: true
            immediate: true
          loop: "{{ satellite_installer_firewall_services }}"
          loop_control:
            loop_var: firewall_service
          when:
            - satellite_installer_firewall_services is defined
        # https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/automating_system_administration_by_using_rhel_system_roles/configuring-kernel-parameters-permanently-by-using-rhel-system-roles
        - name: Disable Transparent Huge Pages (THP)
          ansible.builtin.include_role:
            name: redhat.rhel_system_roles.kernel_settings
            apply:
              tags:
                - os_tasks
          vars:
            kernel_settings_transparent_hugepages: never
            # Set kernel_settings_reboot_ok to false and check
            # variable kernel_settings_reboot_required to determine if reboot is required
            kernel_settings_reboot_ok: false
          tags:
            - always
        - name: Upgrade all packages
          ansible.builtin.dnf:
            name: "*"
            state: latest
        - name: Check that /usr/bin/needs-restarting exists
          ansible.builtin.stat:
            path: /usr/bin/needs-restarting
          register: r_needs_restarting
        - name: Check if reboot required due to package upodates
          ansible.builtin.command: /usr/bin/needs-restarting -r
          register: package_update_reboot_required
          ignore_errors: true
          changed_when: false
          failed_when: package_update_reboot_required.rc not in [0,1]
          when: r_needs_restarting.stat.exists
        - name: Set fact if reboot needed due to package update or kernel changes
          ansible.builtin.set_fact:
            reboot_required: true
          when: |
            (kernel_settings_reboot_required is defined and kernel_settings_reboot_required) or
            (package_update_reboot_required.rc is defined and package_update_reboot_required.rc ==1)
        - name: Reboot the server if needed
          ansible.builtin.reboot:
            msg: "Reboot required to apply updates"
            reboot_timeout: 600
          when:
            - satellite_installer_allow_reboot is defined
            - satellite_installer_allow_reboot | bool
            - reboot_required is defined
            - reboot_required
        - name: Print warning if reboot is required
          ansible.builtin.debug:
            msg: "WARNING: A reboot if required to apply updates and kernel configuration"
          when:
            - (satellite_installer_allow_reboot is not defined) or (satellite_installer_allow_reboot is not true)
            - reboot_required is defined
            - reboot_required
    - name: Run the redhat.satellite_operations roles
      ansible.builtin.include_role:
        name: "{{ __include_role['name'] }}"
        apply:
          tags: "{{ __include_role['tags'] }}"
      when: vars[__include_role.var] is defined
      tags:
        - always
        - installer_tasks
      loop_control:
        loop_var: __include_role
      loop:
        - { name: redhat.satellite_operations.installer, var: satellite_installer_scenario, tags: installer }
        - { name: redhat.satellite_operations.cloud_connector, var: satellite_cloud_connector_url, tags: cloud_connector }
    - name: Print warning if reboot is required
      ansible.builtin.debug:
        msg: "WARNING: A reboot if required to apply updates and kernel configuration"
      when:
        - (satellite_installer_allow_reboot is not defined) or (satellite_installer_allow_reboot is not true)
        - reboot_required is defined
        - reboot_required
      tags:
        - always
...
