---
# satellite_content_credentials:
#   - name: RPM-GPG-KEY-MariaDB
#     content_type: gpg_key
#     content: "{{ lookup('url', 'https://rpm.mariadb.org/RPM-GPG-KEY-MariaDB', split_lines=False) }}"
#   - name: RPM-GPG-KEY-EPEL-8
#     content_type: gpg_key
#     content: "{{ lookup('url', 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8', split_lines=False) }}"
#   - name: RPM-GPG-KEY-EPEL-9
#     content_type: gpg_key
#     content: "{{ lookup('url', 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9', split_lines=False) }}"
#   - name: RPM-GPG-KEY-SPP
#     content_type: gpg_key
#     content: "{{ lookup('url', 'https://downloads.linux.hpe.com/SDR/repo/spp-gen11/GPG-KEY-spp', split_lines=False) }}"
...
