---
# satellite_auth_sources_ldap:
#   - name: "Example LDAP"
#     host: "ldap.example.org"
#     onthefly_register: true
#     account: uid=ansible,cn=sysaccounts,cn=etc,dc=example,dc=com
#     account_password: secret
#     base_dn: dc=example,dc=com
#     groups_base: cn=groups,cn=accounts, dc=example,dc=com
#     server_type: free_ipa
#     attr_login: uid
#     attr_firstname: givenName
#     attr_lastname: sn
#     attr_mail: mail
#     attr_photo: jpegPhoto
#     state: present
#   - name: "Example AD"
#     host: "ad.example.org"
#     onthefly_register: true
#     account: EXAMPLE\ansible
#     account_password: secret
#     base_dn: cn=Users,dc=example,dc=com
#     groups_base: cn=Users,dc=example,dc=com
#     server_type: active_directory
#     attr_login: sAMAccountName
#     attr_firstname: givenName
#     attr_lastname: sn
#     attr_mail: mail
#     ldap_filter: (memberOf=CN=Domain Users,CN=Users,DC=example,DC=com)
#     state: present
...
