---
# satellite_sync_plans:
#   - name: Weekly Sync
#     interval: weekly
#     sync_date: 2020-11-07 00:00:00 UTC
#     products: "{{ satellite_products | map(attribute='name') | list }}"
#     enabled: false
...
